### PR TITLE
anytype warning

### PR DESCRIPTION
**Pull request by CJary**
Added, "noImplicitAny": false to tsconfig.json

### CODE REVIEW

**Comment by curran** [comment]
What issue does this close?

**Comment by CJary** [comment]
If I implemented it correctly, I hope it will fix TypeScript Linting: Ignore "any type" warnings
[#477](https://github.com/vizhub-core/vzcode/issues/477)

**Comment by curran** [comment]
Ah, I see! The change you have made here relates to the config of the VZCode source code itself.

That issue is about this kind of error appearing inside the actual VZCode editor itself.

So to reproduce this, you would run `npm run dev`, then open up a file, then paste the reproduction code, then see the error. To remove that error, we'd need to make a source code change to filter out some of the linter warnings based on the error code. I believe this is already being done, and we probably can solve it by just adding another code to the list that we check already.

See https://github.com/vizhub-core/vzcode/blob/main/src/client/useTypeScript/worker.ts#L240

**Comment by CJary** [comment]
Commit a new version 2/16 4:06pm. Restore the tsconfig.json file. Added the error code into the filter for the array tsErrors. 

Error code was referenced on this website I found:
https://github.com/microsoft/TypeScript/blob/v5.4-beta/src/compiler/diagnosticMessages.json

**Comment by curran** [comment]
Amazing! Thank you so much. I will test it out.

**Comment by curran** [comment]
I'm so happy this is getting resolved, it came up just today when I was recording a lecture video:

image

**Comment by curran** [comment]
Tested it out, and it works! Thank you so much. This is a great improvement to the editor experience.

image

**Pull request merged**
