### PR TITLE
Starting changes for auto-follow open file feature

### PR DESCRIPTION
**Pull request by curran**

### CODE REVIEW

**Comment by DaCatDude** [comment]
openTab isnt being recognized as a function, I followed the imports you suggested here. I think its something really obvious I am missing, but I am not sure what it is. Feels rly close.

**Comment by curran** [comment]
@DaCatDude There's just one last step required here - pass it into `getOrCreateEditor`. If you search the codebase for `getOrCreateEditor` and see where it is being invoked, add it to that list of options and make sure it's in scope. Keep tracing it outward until it connects. Good luck!

**Comment by curran** [comment]
I'll pick this up.

**Comment by curran** [comment]
Got it! Now there's another issue with scrollToCursor... almost there!

image

**Comment by curran** [comment]
Got it totally working woohoo!

**Pull request merged**
