### PR TITLE
added rainbow brackets to the code editor

### PR DESCRIPTION
**Pull request by michaelhelper**
I used the repository linked in the issue: https://github.com/eriknewland/rainbowbrackets.git. The developer has not released a package, so I copied over the JavaScript file and converted it to a typescript file to implement the feature. I also changed the colors that the developer had implemented in favor of higher contrast colors.

I also fixed a spelling error I found while combing through the codebase.

### CODE REVIEW

**Comment by curran** [comment]
Ideally we'd have theme-driven colors

image

See `src/client/themes/vizhubTheme/index.ts`

**Comment by michaelhelper** [comment]
I added a test file to visualize the colors and made a custom color theme for the vizhub theme. I also implemented the np package and deleted the js file.

**Comment by michaelhelper** [comment]
I have been pondering the best implementation of this feature. I am thinking maybe a button to turn them on and off in settings and two sets of colors: colors for light themes and colors for dark themes. Any thoughts from the rest of the development team?

**Review by curran — APPROVED** [review]
LGTM!

**Pull request merged**
