### PR TITLE
WIP Split Pane

### PR DESCRIPTION
**Pull request by michaelhelper**
just a draft.
I added a button and a hacky split pane view

### CODE REVIEW

**Comment by curran** [comment]
Excellent start! Please re-build based on https://github.com/vizhub-core/vzcode/pull/802

That provides a foundation where you can make the icon clicking do something - probably dispatch a new action that transforms the `pane` from a `leafPane` to a `splitPane`. Good luck!

**Comment by curran** [comment]
Actually, I could merge this if we revert the changes commenting out the DOM removal AND put the new icon behind a feature flag. Ideally the icon could represent a split pane. The "+" symbol may not be the best.

**Comment by michaelhelper** [comment]
VScode icon for split view: 
image

**Comment by michaelhelper** [comment]
* new action type
* call reducer (ex set active file id)
* Utilize find pane
* new update pane function - new similar split pane function

**Comment by curran** [comment]
Added my commit. Back to you!

**Pull request merged**
